<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.php">Stockholm</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="index.php">Home</a></li>
      <li><a href="attractions.php">Attractions</a></li>
      <li><a href="restaurants.php">Restaurants</a></li>
      <li><a href="shopping.php">Shopping</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="login.php"><span class="glyphicon glyphicon-user"></span>Login or Sign Up!!</a></li>
      
    </ul>
  </div>
</nav>