  
<div class="snlnk">
    <a class="apple" href="login.php">Log In or Sign Up Here!</a> 
</div>

<div class = "logo"><a href="index.php"><img src="images/logo.png" alt ="Logo"> </a> 
	</div>

<nav class = "menu">
	<ul>
		<li><a href="index.php">Home</a></li>
  <li><a href="attractions.php">Attractions</a></li>
  <li><a href="restaurants.php">Restaurants</a></li>
  <li><a href="shopping.php">Shopping</a></li>
 
		
	</ul>


</nav>



