	<div class="Head">

<a href="login.php" class="button">Login or SignUp!</a>		  

<div class = "logo"><a href="index.php"><img src="images/logo.png" alt ="Logo"> </a> 
	</div>

<nav class = "menu">
	<ul>
		<li><a href="index.php">Home</a></li>
  <li><a href="attractions.php">Attractions</a></li>
  <li><a href="restaurants.php">Restaurants</a></li>
  <li><a href="shopping.php">Shopping</a></li>
 
		
	</ul>


</nav>
</div>


